# --- The Correct docker-compose.yml ---

version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    # REPLACE the 'environment' block with 'env_file'
    env_file:
      - ./.env
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: